### ISSUE TITLE
Change preprocessing to the new ProcessList

### ISSUE THREAD

**Issue by spillerrec** [spillerrec/Overmix#125]
Might as well reuse the post-processing UI for preprocessing as well.

**Tasks:**
- [x] Add cropping as an AProcessor
- [x] Add De-VLC as an AProcessor
- [x] AProcessor needs to support offset transformation
